### ISSUE TITLE
import anything which can be required from node

### ISSUE THREAD

**Issue by safareli** [Updater/node-sass-json-importer#14]
What if we import any file which could be required? For example if user of this lib has registered `xml`, `yaml`, `ini` or some other extension handler in `require.extensions` then just import it and don't stick to only json extension.

If so user could import js and json files or if he/she registers any other extension, user would be able to import it as well. For example [better-require](https://www.npmjs.com/package/better-require) registers handlers to some data files.

**Comment by safareli** [comment]
if that's ok name of this repo will be irrelevant because this will not only import json but anything that's requirable.

**Comment by pmowrer** [comment]
Sorry to say, but that's outside the scope of this repo. This repo is more [require-json](https://github.com/olalonde/require-json) to a [better-require](https://www.npmjs.com/package/better-require) (which I guess doesn't exist for `node-sass` importers).
