### ISSUE TITLE
importer does not import any of the files

### ISSUE THREAD

**Issue by rob-bar** [Updater/node-sass-json-importer#17]
I have a very strange issue, when using your importer.
I use it within the gulp-sass task runner.
in this repo https://github.com/Crosscheck/Jacket
on my install the importer works fine, and on an install of my colleague the importer does not import a single file, do you have any ideas what this could be?
Is this related to the feature of node-sass being experimental?
Is there any way I can test this or maybe fix the issue myself?

These are the packages that are used:
```json
    "browser-sync": "^2.9.6",
    "chalk": "^1.1.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-help": "^1.6.1",
    "gulp-minify-css": "^1.2.2",
    "gulp-sass": "^2.0.4",
    "gulp-sass-glob": "0.0.2",
    "gulp-scss-lint": "^0.3.0",
    "gulp-sequence": "^0.4.1",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-util": "^3.0.7",
    "node-bourbon": "^4.2.3",
    "node-neat": "^1.7.2",
    "node-normalize-scss": "^1.0.3",
    "node-sass-json-importer": "^1.0.2",
    "sassdoc": "^2.1.15",
    "terminal-notifier": "^0.1.2"
```

**Comment by rob-bar** [comment]
Ok, maybe the issue is double quotes or single quotes, another colleague of mine said to look in that direction.

**Comment by rob-bar** [comment]
Does your importer require singel quote ussage?

**Comment by pmowrer** [comment]
Can you provide an example of how the importer is applied/configured?

**Comment by rob-bar** [comment]
Hey Patrick,

You can find the project / implementation here, 
https://github.com/Crosscheck/Jacket
The gulpfile with the config here:
https://github.com/Crosscheck/Jacket/blob/master/gulpfile.js
and the specific json import here:
https://github.com/Crosscheck/Jacket/blob/master/src/scss/utils/variables/_neat.scss

On that topic, another colleague of me said that it had to do something with single or double quotes.
Could these quotes be an issue?

**Comment by pmowrer** [comment]
Thanks, and is there an error message or anything to show how it isn't working?

**Comment by rob-bar** [comment]
There is no error, my css files are just empty.

**Comment by pmowrer** [comment]
What is the expectation? Output from https://github.com/Crosscheck/Jacket/blob/master/src/scss/utils/variables/_neat.scss? It looks like it only has variables, no actual CSS. 

Sorry @rob-bar, but I can't help unless you can provide a more detailed description of the problem and how to reproduce (e.g. step-by-step instructions to demonstrate the problem).

**Comment by rob-bar** [comment]
Ok, so what you need to do is clone 'Jacket' the repo, 
1) `git clone git@github.com:Crosscheck/Jacket.git` 
1a) you should have nodejs installed. If not you can download it on their homepage. v4.2.x is fine
2) then you should run `npm install -g gulp`, this installs the gulp CLI tool globally 
3) You should also install the scss_lint gem by `gem install scss_lint`
4) run `npm install` in the root of the repo.
5) then run `gulp`.

That should run all tho correct commands. You should see this, http://dl.getdropbox.com/u/7422112/screenshots/Screen%20Shot%202016-01-11%20at%2008.45.01.png
And then your browser should pop up on localhost:3000 with an index page.

It is true that the neat file only contains variables, but this neat file is used by many other files, take a look at those files in the root of the scss folder.(base-styles.scss for example)
There you will see that those variables are all imported by the globbing technique.
`@import "utils/variables/*";`

So, I re-encountered the problem with another colleague of mine, also with him it does not export a single line of css. After removing your importer and making sure that the breakpoints.json that we made is converted to a sass list at the top of the neat.scss file everything works like it should, 
css is compiled in a normal fashion.

The problem is that I can't reproduce the bug either, I am almost certain that is its related to one having a specific version of either node, node-sass, libsass or any other lib. That is why I need your help because you maybe know which version your module needs.

Let me know if you get any errors.
BTW: The scss is compiled to /dist/css

**Comment by rob-bar** [comment]
My goal is to make all the breakpoints in a single json file (breakpoints.json) and then use that file in scss and js. So the configuration of that file is in one place. That is the main goal here.

**Comment by rob-bar** [comment]
I found the issue, it was the version of node, thank you

**Comment by pmowrer** [comment]
Glad to hear it was resolved!

**Comment by chrislopresto** [comment]
@rob-bar I'm experiencing the same issue on recent master versions of node-sass. Would you mind sharing details as to what caused and solved your problems?

Thanks!

**Comment by rob-bar** [comment]
The problem was the node version, when we upgraded to node 5.x.x the problem was solved.
Let me know if you have any other trouble or when you succeed. :)

**Comment by chrislopresto** [comment]
Thanks, @rob-bar. I was using node 5.6.0 already, so that wasn't it for me. 

I did track down an explanation for my problem.. details here: https://github.com/Updater/node-sass-json-importer/pull/24

**Comment by rob-bar** [comment]
Nice! Thx for the update
