### ISSUE TITLE
JSON import not working

### ISSUE THREAD

**Issue by akikoo** [Updater/node-sass-json-importer#19]
Hi,

Thanks for your good work - I'd really like to use this importer for shared config for Sass and JS but I'm having trouble setting it up. Basically I can't figure out how to make this work with node-sass CLI `--importer`. I'm running on `node v5.5.0`, `node-sass v3.4.2` and `node-sass-json-importer v1.0.5`. 

I'm compiling Sass like so: `./node_modules/.bin/node-sass --importer ./src/shared/styles/json_importer --recursive ./src --output ./compiled`

```
// json_importer.js
var sass = require('node-sass');
var jsonImporter = require('node-sass-json-importer');

module.exports = sass.render({
  file: 'src/shared/styles/base.scss',
  importer: jsonImporter
}, function(err) {
  if (err) {
    console.log('Error: ', err);
  }
});
```
Then when I'm trying to import a json config file in my Sass file like so: `@import "config.json";`, I get the following error: `"Error: Invalid CSS after \"\": expected 1 selector or at-rule, was \"{\"\n        on line 1 of src/shared/styles/config.json\n>> {\n   ^\n"`

Any help or pointers would be appreciated, I need to get this working :) 

I'm not completely comfortable with node-sass importer so maybe I'm doing something wrong there?

Cheers!

**Comment by pmowrer** [comment]
I haven't tried using the cli before, but trying to compile one of the test files in this repo:

```bash
./node_modules/.bin/node-sass --importer ./dist/node-sass-json-importer.js ./test/fixtures/strings/style.scss
```
```bash
body {
  color: #c33; }
```

Looks like you're mixing cli and api usage? 

Try pointing `--importer` at `node_modules/node-sass-json-importer/dist/node-sass-json-importer.js`.

**Comment by akikoo** [comment]
Well that was an easy fix, it works fine now :) I was making this more difficult than it was. Thanks a lot!

Maybe it's a good idea to add an example of CLI usage? I've opened a pull request for that: https://github.com/Updater/node-sass-json-importer/pull/20

Thanks again!

**Comment by pmowrer** [comment]
Glad it was easy!
