### ISSUE TITLE
Importer caches files

### ISSUE THREAD

**Issue by LPGhatguy** [Updater/node-sass-json-importer#21]
This is only a problem when working with continuous rebuild systems like Gulp and Grunt.

node-sass-json-importer uses `require` to load JSON files, which caches results. The plugin should either:

1. Not use require to load JSON (ideal)
2. Clear the require cache entry for the JSON file on every load

**Comment by esr360** [comment]
Perhaps this is the issue I am experiencing right now...I have a setup similar to the following:

[module1
----[config.json
----[module1.scss
[module1
----[config.json
----[module2.scss

Which doesn't seem to work properly when using a continuous rebuild system. However, changing to the following seems to work:

[module1
----[module1.json
----[module1.scss
[module1
----[module2.json
----[module2.scss

However, ideally, I would like to stick with the first option if possible.

Is anyone able to confirm my issue?
