### ISSUE TITLE
includePaths not correctly parsed on windows

### ISSUE THREAD

**Issue by ychailler** [Updater/node-sass-json-importer#44]
Using includePaths in a Windows environment does not work as it is parsed using a ':' separator : 
  var includePaths = this.options.includePaths ? this.options.includePaths.split(':') : [];

The separator should be replaced by _path.delimiter that takes into account environment specific separator.
  var includePaths = this.options.includePaths ? this.options.includePaths.split(_path.delimiter) : [];

**Comment by pmowrer** [comment]
Good catch! I'll get to it soon, else feel free to submit a PR. Here's the relevant Node API call https://nodejs.org/api/path.html#path_path_delimiter

**Comment by efeminella** [comment]
Any updates on this? It's a blocker for team members who are on Windows!

**Comment by efeminella** [comment]
Hey Guys, I just put in a quick PR which resolves this.

**Comment by pmowrer** [comment]
Thanks for the fix @efeminella! Published as v3.0.2.
