### ISSUE TITLE
Issues when impoting multiple json files with same name/keys

### ISSUE THREAD

**Issue by esr360** [Updater/node-sass-json-importer#50]
Potentially related to: https://github.com/Updater/node-sass-json-importer/issues/21

I've noticed some issues with the wrong file being read/imported if the project has multiple files with the same name, like this:

[module1/
----[config.json
----[module1.scss
[module1/
----[config.json
----[module2.scss

I've also noticed issues when using multiple files with different names when the contents begin with the same first key, like this:

[module1/
----[module1.json
----[module1.scss
[module1/
----[module2.json
----[module2.scss

Where both module1.json and module2.json start like this:

    {
        "default": {
            ...
        }
    }

Sometimes the wrong json file will be imported, which obviously breaks the compilation.

My ideal setup would be for all my json files to be named `config.json` and begin with the `default` key, but as it stands I have to have unique names for both the file name and opening key.

**Comment by pmowrer** [comment]
Sorry we never followed up on this @esr360! If its still something you'd like to try to fix, please re-open with a reproducible scenario.
