### ISSUE TITLE
Problem with single dash

### ISSUE THREAD

**Issue by soelen** [Updater/node-sass-json-importer#54]
Hello there, I accidently created an issue ticket in a wrong repository, the people from gulp-sass-import-json were still kind and tried to help :)

https://github.com/acusticdemon/gulp-sass-import-json/issues/7

Longs to short: When I add just a single dash in a value node-sass seems to have a problem to process the json file:

![JSON](https://user-images.githubusercontent.com/1114549/36542210-71825052-17e0-11e8-9bac-55c289db73c0.png)

![Console outpout](https://user-images.githubusercontent.com/1114549/36542218-7cfaa286-17e0-11e8-845a-d08d6f58c4ad.png)

**Comment by pmowrer** [comment]
Hi @soelen! I guess `-` isn't a valid value for a SASS variable? Unfortunately, SASS handles strings ambiguously and its difficult for us to determine what the intention is in JSON. Almost all of the issues that come up concern strings.

There is a workaround that always works: If it's intended to be a string, wrap it in single quotes. 

```json
"shadePrefix": "'-'" 
```

More about handling strings here: https://github.com/Updater/node-sass-json-importer#importing-strings
