### ISSUE TITLE
Import array

### ISSUE THREAD

**Issue by spernigotti** [Updater/node-sass-json-importer#61]
I have the following json file:
_colors.json_
`[{
	"id": 1
},{
	"id": 2
}]`
when I import it in sass, the response is:
`$0: (id: 1);
$1: (id: 2);`
this is because the keys of array are numerical, and variables numerical in sass are invalid.
I propose in these cases that the result is a variable with the name of the file, in my example is _$colors_.
`$colors: ((id: 1),(id:2));`

**Comment by pmowrer** [comment]
Closed by #62
