### ISSUE TITLE
Single-element lists update breaks zero-element lists

### ISSUE THREAD

**Issue by rasenplanscher** [Updater/node-sass-json-importer#67]
After updating to v3.3.0, I get this error for empty lists/arrays:
```
Invalid CSS after "$options: (": expected expression (e.g. 1px, bold), was ",);"
```

This seems to be due to the update enabling single-element lists.

**Comment by pmowrer** [comment]
@dentrado Do you think this is something that can be easily resolved or do we need to revert?
