### ISSUE TITLE
can't import hsl colors properly

### ISSUE THREAD

**Issue by safareli** [Updater/node-sass-json-importer#7]
because it contains `,` it is wrapped in  quotes and then if you use it with `fade-out` for example would get error:
```
argument `$color` of `fade-out($color, $amount)` must be a color
```
https://github.com/Updater/node-sass-json-importer/blob/v1.0.3/src/index.js#L41

**Comment by safareli** [comment]
i think we should first match if contains parentheses `.match(/[()]/)` and then for comma and whitespace

**Comment by safareli** [comment]
or update the line to this
```
} else if (_lodash2['default'].isString(value) && value.match(/[\s,]/) && !value.match(/[()]/)) {
```

**Comment by pmowrer** [comment]
@safareli What does the JSON look like?

**Comment by safareli** [comment]
{
  white: "hsl(0,0%,100%)"
}

**Comment by safareli** [comment]
If solution is ok I can create PR

**Comment by safareli** [comment]
some edge cases:

in: `{ "namedColor" : "gold" }`
out: `$namedColor: "gold";`
User of this library may thought to use it as color but it is compiled to string so she can't.

---

in:  `{ "containingQuotes" : "\"qu'ote"}`
out: `$containingQuotes: "qu'ote;`
Desired output will be to wrap in quotes.

---

in: `{ "escapedChar" : "\\26"}`
out: `$escapedChar: \26;`
It's desired behaviour

---

in: `{ "escapedCharWithSpace" : "bar \\26 foo"}`
out: `$escapedCharWithSpace: "bar \26 foo";` 
if it's quoted and $escapedChar not it's confusing

---

I think simplest and most consistent way will be to not wrap any value in quotes and if user wants it to be wrapped will put it in quotes like this.
in: `{ "foo": "'some , text \\26 foo'" }`
out: `$foo: 'some , text \26 foo'`

or

in: `{ "foo": "\"some , text \\26 foo\"" }`
out: `$foo: "some , text \26 foo"`

so user can control output himself if he wants to use `rgb(0,0,0)` as string will wrap it in quotes
in: `{ "foo": "\"rgb(0,0,0)\"" }`
out: `$foo: "rgb(0,0,0)"`

or if he wants could embed sass map in it too or function call or whatever

i'll close this issue and PR of this and create another one for this solution

**Comment by safareli** [comment]
I think we should just apply  PR #5 and it will solve this issue. also I have [commented](https://github.com/Updater/node-sass-json-importer/pull/5#issuecomment-154049414) solution that issue
